name: flowmart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  video_player: ^2.8.6
  go_router: ^17.0.1
  provider: ^6.1.5+1
  font_awesome_flutter: ^10.12.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  email_otp: ^3.1.0
  firebase_messaging: ^16.1.0
  cloud_firestore: ^6.1.1
  model_viewer_plus: ^1.9.3
  firebase_storage: ^13.0.5
  image_picker: ^1.2.1
  flutter_ai_toolkit: ^1.0.0
  google_generative_ai: ^0.4.7
  firebase_ai: ^3.6.1
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# --- Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø© Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø© (ØªÙ… Ø¯Ù…Ø¬ Ø§Ù„Ø®Ù„ÙÙŠØ©) ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/logo.jpg"
  min_sdk_android: 21
  # ðŸ‘‡ Ù‡Ù†Ø§ ÙˆØ¶Ø¹Ù†Ø§ Ù„ÙˆÙ† ÙƒØ­Ù„ÙŠ ØºØ§Ù…Ù‚ Ù‚Ø±ÙŠØ¨ Ù…Ù† Ù„ÙˆÙ† Ø´Ø¹Ø§Ø±Ùƒ Ù„Ø¯Ù…Ø¬ Ø§Ù„Ø­ÙˆØ§Ù
  adaptive_icon_background: "#0B2447" 
  adaptive_icon_foreground: "lib/assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: lib/assets/fonts/Urbanist-Bold.ttf
        - asset: lib/assets/fonts/Urbanist-Medium.ttf
        - asset: lib/assets/fonts/Urbanist-Regular.ttf